language: elixir
os: linux
dist: xenial
jobs:
  include:
    - elixir: 1.4
      otp_release: 19.3
    - elixir: 1.10
      otp_release: 22.0
env: MIX_ENV=test
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix test
